on: [pull_request, merge_group]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: zig env
      - run: ls ~/.cache/zig/p
      - run: zig build -Dci --fetch=all
      - run: ls ~/.cache/zig/p
      - run: zig build -Dci
      - run: zig build test -Dci
      - run: zig build -Dci -Dtarget=x86_64-windows -p build/windows
      - run: zig build -Dci -Dplatform=web -p build/web
      - run: ./gradlew assembleDebug
        working-directory: packages/android/Aztest
      - run: mkdir -p build/android && cp packages/android/Aztest/app/build/outputs/apk/debug/app-debug.apk build/android
      - uses: actions/upload-artifact@v4
        with:
          path: build

