on: [pull_request, merge_group]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
          use-cache: false
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Download packages
        run: |
          mkdir -p ~/.cache/zig
          wget -O blockeditor-packages.zip https://unalfs.b-cdn.net/by-name/blockeditor-packages-0.zip
          echo "344435a7e9d8c924688cac67246d08838a00361280e7a6c81710ddd226d0d400 *blockeditor-packages-0.zip" | shasum -a 256 --check --status
          unzip -o blockeditor-packages.zip -d ~/.cache/zig/
      - name: Build with Zig (network disabled)
        run: |
          unshare -n bash -c '
            zig build -Dci &&
            zig build test -Dci &&
            zig build -Dci -Dtarget=x86_64-windows -p build/windows &&
            zig build -Dci -Dplatform=web -p build/web
          '
      - run: unset ZIG_LOCAL_CACHE_DIR; ./gradlew assembleDebug
        working-directory: packages/android/Aztest
      - run: mkdir -p build/android && cp packages/android/Aztest/app/build/outputs/apk/debug/app-debug.apk build/android
      - uses: actions/upload-artifact@v4
        with:
          path: build

