on: [pull_request, merge_group]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
          use-cache: false
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Download packages
        run: |
          mkdir -p ~/.cache/zig &&
          echo "Download..." &&
          wget -q -O blockeditor-packages-0.tar.xz https://unalfs.b-cdn.net/by-name/blockeditor-packages-0.tar.xz &&
          echo "Shasum..." &&
          echo "d03337940503f5a0c33df65528ff6f01920f5ff79ba8c79842932118873459ce *blockeditor-packages-0.tar.xz" | shasum -a 256 --check --status &&
          echo "Extract..." &&
          tar -xJf blockeditor-packages-0.tar.xz -C ~/.cache/zig/ &&
          echo "Done"
      - run: zig build -Dci
      - run: zig build test -Dci
      - run: zig build -Dci -Dtarget=x86_64-windows -p build/windows
      - run: zig build -Dci -Dplatform=web -p build/web
      - run: unset ZIG_LOCAL_CACHE_DIR; ./gradlew assembleDebug
        working-directory: packages/android/Aztest
      - run: mkdir -p build/android && cp packages/android/Aztest/app/build/outputs/apk/debug/app-debug.apk build/android
      - uses: actions/upload-artifact@v4
        with:
          path: build

